#define MANUX_NB_HANDLER_PAR_IRQ 4
#define MANUX_NB_IRQ 16
#define MANUX_CONSOLE 
#define MANUX_CONFIG 
#define MANUX_PAGINATION 
#define MANUX_CLAVIER 
#define MANUX_RAMDISK 
#define MANUX_FICHIER 
#define MANUX_NB_MAX_FICHIERS 4
#define MANUX_VIRTIO_CONSOLE 
#define MANUX_INIT_MAGIC 0x01c0ffee
#define MANUX_TACHE_CONSOLE 
#define MANUX_JOURNAL 
#define MANUX_TAILLE_PAGE 0x1000
#define MANUX_APPELS_SYSTEME 
#define MANUX_CONSOLES_VIRTUELLES 
#define MANUX_NB_EXCEPTIONS 32
#define MANUX_JOURNAL_NIVEAU_DEFAUT 7
#define MANUX_HERITER_FICHIERS 
#define MANUX_HANDLER_IRQ i8259aGestionIRQ
#define MANUX_PCI 
#define MANUX_AS_AUDIT 
#define MANUX_NB_SECT_RAMDISK 0x2
#define MANUX_ADRESSE_IDT 0x41000
#define MANUX_INT_BASE_IRQ MANUX_NB_EXCEPTIONS
#define MANUX_CLAVIER_CONSOLE 
#define MANUX_PREMIER_SECT_RAMDISK 0x10
#define MANUX_PIC INTEL_8259A
#define MANUX_TACHES 
#define MANUX_ATOMIQUE_AUDIT 
#define MANUX_INT_AUDIT 
#define MANUX_SEGMENT_TRANSIT_RAMDISK 0x4000
#define MANUX_PIC_INIT i8259aInit
#define MANUX_KMALLOC kmalloc-zs
#define MANUX_LIBI386 
#define MANUX_INOEUDS 
#define MANUX_TAILLE_PILE 16384
#define MANUX_IDT_NB_PAGES 1
#define MANUX_GESTION_MEMOIRE 
#define MANUX_REENTRANT 
#define MANUX_NB_MAX_EQUIPEMENTS_PCI 32
#define MANUX_NB_CYCLES_CALIBRAGE MANUX_FREQUENCE_HORLOGE
#define MANUX_BOOT_START_ADDRESS 0x7c00
#define MANUX_ELF_HEADER_SIZE 0x80
#define MANUX_ADRESSE_BIOS 0x80000
#define MANUX_INIT_START_ADDRESS 0x7e00
#define MANUX_VIRTIO 
#define MANUX_PRINTK 
#define MANUX_CONSOLE_MAJEUR 0
#define MANUX_JOURNAL_DIRECT_CONSOLE 
#define MANUX_KERNEL_START_ADDRESS 0x20000
#define MANUX_NB_SECT_INIT 0x02
#define MANUX_PREEMPTIF 
#define MANUX_FREQUENCE_HORLOGE 100
#define MANUX_TUBE_REENTRANT 
#define MANUX_AFFECTATION_PAGES 0x1000
#define MANUX_USR 
#define MANUX_STACK_SEG_16 0x9000
#define MANUX_ADRESSE_GDT 0x42000
#define MANUX_GDT_NB_PAGES 1
#define MANUX_NB_INTERRUPTIONS 256
#define MANUX_USR_INIT init-acces-concurrent.o
#define MANUX_BASCULER_NOUVELLE_CONSOLE 
#define MANUX_TUBES 
#define MANUX_ATOMIQUE 
#define MANUX_ASSERT_ACTIVES 
#define MANUX_STDLIB 
#define MANUX_NOMBRE_PAGES_SYSTEME 0x800
#define MANUX_VIRTIO_CONSOLE_MAJEUR 1
#define MANUX_ADRESSE_ECRAN 0xb8000
#define MANUX_KMALLOC_STAT 
#define MANUX_BOOTLOADER 
#define MANUX_FICHIER_MAIN main-acces-concurrent
#define MANUX_BIOS_NB_PAGES 0x80
